name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into VM and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -T git@github.com
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key root@83.222.9.213 << 'EOF'
            cd /root/flowers-api
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            git pull origin master
            sudo docker build -t myapp .
            sudo docker run -d -p 7777:7777 --name myapp myapp
          EOF